name: biblioteca_framework_flutter_github_io
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  dio: any
  flutter_mobx: any
  mobx: any
  flutter_modular: any

  shared_preferences: any
  sqflite: ^1.2.0

  fab_circular_menu: any
  intl: any
  badges: any

  flare_flutter: any

  provider: any

  syncfusion_flutter_charts: any
  table_calendar: ^2.2.3

  audioplayers: any
  image_picker: any

  cpf_cnpj_validator: any
  autocomplete_textfield: any

  google_maps_flutter: any
  geolocator: ^5.3.0

  datetime_picker_formfield: ^1.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  mockito: any
  mobx_codegen: any
  build_runner: any
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/MortalkombatLogo.png
   - assets/scorpion.jpg
   - assets/subzeroperfil.jpg
   - assets/icons/Clone-Old-icon.png
   - assets/icons/Darth-Vader-icon.png
   - assets/images/flutterSplash01.png
   - assets/images/flutterSplash02.png
   - assets/audios/SoundHelix.mp3
   - assets/images/parar.png
   - assets/images/pausar.png
   - assets/images/executar.png
   - assets/flare_loading.flr
   - assets/mortal.flr  

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal
